name: lions_den_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.7
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.0.0
  firebase_auth: ^1.1.2
  firebase_core: ^1.1.0
  flutter_chat_ui: ^1.0.2
  flutter_icons: ^1.1.0
  flutter_password_strength: ^0.1.6
  flutter_riverpod: ^0.14.0+3
  flutter_snake_navigationbar: ^0.5.0
  hexcolor: ^2.0.3
  jiffy: ^4.1.0
  lint: ^1.5.3
  persistent_bottom_nav_bar: ^4.0.2
  simple_animations: ^3.1.1
  smooth_page_indicator: ^0.2.1
  supercharged: ^2.0.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - messages.json
